document.querySelectorAll('.project-card--flip').forEach((card) => {
    const flips = card.querySelectorAll('.project-card__flip');
    flips.forEach((button) => {
    button.addEventListener('click', (event) => {
        event.preventDefault();
        event.stopPropagation();
        card.classList.toggle('is-flipped');
    });
    });
});

document.querySelectorAll('.project-card').forEach((card) => {
    const overlay = card.querySelector('.project-card__overlay');
    if (overlay) {
    card.addEventListener('click', (event) => {
        if (event.target.closest('.project-card__flip, .project-card__arrow')) {
        return;
        }
        overlay.click();
    });
    }
});

/*
    Letterboxd live feed
    ─────────────────────────────────────────────────────────────
    Fetches the last 4 diary entries from the public RSS feed at
    https://letterboxd.com/tomnewbold/rss/ via allorigins.win,
    a free CORS proxy that returns the raw XML as a JSON string.

    Letterboxd's RSS includes dedicated namespace elements:
    <letterboxd:filmTitle>   film title
    <letterboxd:filmYear>    release year
    <letterboxd:memberRating> rating 0–5 (float, e.g. 4.5)
    The film poster is an <img> inside the CDATA description block.

    If the fetch fails (proxy down, network issue) the section shows
    a fallback link to the Letterboxd profile instead.
*/
(async function loadLetterboxd() {
    const container = document.getElementById('lb-films-list');
    if (!container) return;

    const USERNAME = 'tomnewbold';
    const COUNT    = 4;
    const RSS_URL  = `https://letterboxd.com/${USERNAME}/rss/`;

    /*
    corsproxy.io returns the raw feed as text — no JSON wrapper — which
    means the XML goes straight into DOMParser without any encoding issues.
    allorigins.win (previous proxy) wraps in JSON and can mangle namespaces.
    */
    const PROXY = `https://corsproxy.io/?${encodeURIComponent(RSS_URL)}`;

    try {
    const resp = await fetch(PROXY);
    if (!resp.ok) throw new Error(`Proxy responded ${resp.status}`);

    const xmlText = await resp.text();
    const xml     = new DOMParser().parseFromString(xmlText, 'text/xml');

    /* DOMParser never throws — on failure it returns a <parsererror> document */
    const parseErr = xml.querySelector('parsererror');
    if (parseErr) throw new Error(`XML parse failed: ${parseErr.textContent.slice(0, 80)}`);

    const items = [...xml.querySelectorAll('item')].slice(0, COUNT);
    if (!items.length) throw new Error('RSS returned no items');

    container.innerHTML = items.map(item => {
        /* ── Film metadata ── */
        const filmTitle =
        item.getElementsByTagName('letterboxd:filmTitle')[0]?.textContent?.trim()
        ?? parseTitleFallback(item.querySelector('title')?.textContent ?? '');

        const filmYear =
        item.getElementsByTagName('letterboxd:filmYear')[0]?.textContent?.trim() ?? '';

        const ratingRaw = parseFloat(
        item.getElementsByTagName('letterboxd:memberRating')[0]?.textContent ?? '0'
        );

        /* ── Poster: Letterboxd puts <img> inside the CDATA description ── */
        const descCdata = item.querySelector('description')?.textContent ?? '';
        const tmp = document.createElement('div');
        tmp.innerHTML = descCdata;
        const posterSrc = tmp.querySelector('img')?.src ?? '';
        const review = tmp.querySelectorAll('p')[1] ?? '';

        const reviewLines = review?.innerHTML
        ? review.innerHTML
            .split(/<br\s*\/?>/i)
            .map(part => part.replace(/<[^>]+>/g, '').trim())
            .filter(Boolean)
        : [];

        /* ── Entry link ──
            In RSS, <link> is a sibling text node and notoriously awkward
            to read via querySelector in XML mode. <guid> holds the same URL
            and is a normal element, so use it as the primary source.        */
        const filmLink =
        //item.querySelector('guid')?.textContent?.trim()
        item.querySelector('link')?.textContent?.trim()
        ?? `https://letterboxd.com/${USERNAME}/`;

        /* ── Build poster HTML ── */
        const posterHtml = posterSrc
        ? `<img src="${posterSrc}" alt="${filmTitle}" loading="lazy">`
        : '🎥';

        /* ── Build rating HTML ── */
        const ratingHtml = ratingRaw
        ? `<span class="lb-film__rating">${starsFromRating(ratingRaw)}</span>`
        : '';

        const metaParts = [filmYear, ratingHtml].filter(Boolean).join(' · ');

        //console.log(item.querySelectorAll('letterboxd\\3AwatchedDate'))
        //const watchDate = item.querySelector('letterboxd\\3AwatchedDate')?.textContent?.trim() ?? ''; // e.g. "2026-06-26"
        const autogeneratedReview = review.textContent?.trim().startsWith('Watched on '); // + new Date(watchDate).toLocaleDateString("en-GB", { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }); // e.g. "Watched on Thursday June 25, 2026."
        const reviewHtml = review && !autogeneratedReview && reviewLines.length
        ? reviewLines.map(line => `<p class="lb-film__review">${line}</p>`).join('')
        : '';

        return `
        <a class="lb-film"
            href="${filmLink}"
            target="_blank"
            rel="noopener"
            title="${filmTitle}">
            <div class="lb-film__poster">${posterHtml}</div>
            <div class="lb-film__info">
            <div class="lb-film__title">${filmTitle}</div>
            <div class="lb-film__meta">${metaParts}</div>
            <div class="lb-film__meta">${reviewHtml}</div>
            </div>
        </a>`;
    }).join('');

    } catch (err) {
    console.warn('Letterboxd RSS fetch failed:', err);
    container.innerHTML = `
        <div class="lb-error">
        Couldn't load films right now.
        <a href="https://letterboxd.com/${USERNAME}/"
            target="_blank" rel="noopener">View on Letterboxd →</a>
        </div>`;
    }
}());

/* "Tom rated Interstellar ★★★★½" → "Interstellar" */
function parseTitleFallback(s) {
    return s
    .replace(/^.+? (?:watched|rated|reviewed) /i, '')
    .replace(/ [\u2605\u00BD\u2729].*$/, '')
    .trim();
}

/* 4.5 → "★★★★½✩"   3.0 → "★★★✩✩" */
function starsFromRating(n) {
    const full  = Math.floor(n);
    const half  = (n % 1) >= 0.5;
    //const empty = 5 - full - (half ? 1 : 0);
    return '★'.repeat(full) + (half ? '½' : '');// + '✩'.repeat(empty);
}